namespace Mashd.Frontend.AST;

public enum OpType
{
    Add,
    Subtract,
    Multiply,
    Divide,
    Modulo,
    Equality,
    Inequality,
    LessThan,
    LessThanEqual,
    GreaterThan,
    GreaterThanEqual,
    LogicalOr,
    LogicalAnd,
    NullishCoalescing,
    Negation,
    Not,
    PostIncrement,
    PostDecrement,
    PreIncrement,
    PreDecrement,
    AddAssign,
    SubtractAssign,
    MultiplyAssign,
    DivideAssign,
    NullCoalesceAssign,
}