//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Mashd.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MashdParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMashdListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] MashdParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] MashdParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinition([NotNull] MashdParser.DefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinition([NotNull] MashdParser.DefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MashdParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MashdParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] MashdParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] MashdParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.logicalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalExpression([NotNull] MashdParser.LogicalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.logicalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalExpression([NotNull] MashdParser.LogicalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] MashdParser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] MashdParser.EqualityExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.relationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationExpression([NotNull] MashdParser.RelationExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.relationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationExpression([NotNull] MashdParser.RelationExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.binaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryExpression([NotNull] MashdParser.BinaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.binaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryExpression([NotNull] MashdParser.BinaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.multiplyExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplyExpression([NotNull] MashdParser.MultiplyExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.multiplyExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplyExpression([NotNull] MashdParser.MultiplyExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] MashdParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] MashdParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpression([NotNull] MashdParser.PostfixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpression([NotNull] MashdParser.PostfixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] MashdParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] MashdParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.keyValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyValuePair([NotNull] MashdParser.KeyValuePairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.keyValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyValuePair([NotNull] MashdParser.KeyValuePairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] MashdParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] MashdParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] MashdParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] MashdParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] MashdParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] MashdParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MashdParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] MashdParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MashdParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] MashdParser.IdentifierContext context);
}
